# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('parent', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=430)),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images')),
                ('photo_content_type', models.CharField(blank=True, max_length=50)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='socialnetwork.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
